import { Card } from '../types/game';

/**
 * AI difficulty levels for boardgame.io's MCTS bot
 */
export enum AIDifficulty {
  NOVICE = 'novice',
  EASY = 'easy',
  MEDIUM = 'medium',
  HARD = 'hard',
  NIGHTMARE = 'nightmare'
}

/**
 * Represents a move generated by the enumerate function
 */
export interface AIMove {
  cards: string[];     // Card IDs
  column: number;      // Target column
  isStake: boolean;    // Whether this is a stake move
}

/**
 * Configuration options for MCTS bot
 */
export interface MCTSConfig {
  iterations?: number;    // Number of iterations for MCTS
  playoutDepth?: number;  // Depth of playouts
  seed?: string;          // Random seed
}